### ISSUE TITLE
Error when no results are found

### ISSUE THREAD

**Issue by RobinHaveneers** [Jense5/MP3-Downloader#5]
```
download we dont have to take our clothes off whipped cream remix 
? Choose a song to download: (Use arrow keys)


/usr/local/lib/node_modules/mp3-downloader/node_modules/rx-lite/rx.lite.js:75
    throw e;
    ^

TypeError: Cannot read property 'length' of null
    at ScreenManager.render (/usr/local/lib/node_modules/mp3-downloader/node_modules/inquirer/lib/utils/screen-manager.js:65:52)
    at Prompt.render (/usr/local/lib/node_modules/mp3-downloader/node_modules/inquirer/lib/prompts/list.js:102:15)
    at Prompt._run (/usr/local/lib/node_modules/mp3-downloader/node_modules/inquirer/lib/prompts/list.js:73:8)
    at Prompt.run (/usr/local/lib/node_modules/mp3-downloader/node_modules/inquirer/lib/prompts/base.js:55:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/mp3-downloader/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/usr/local/lib/node_modules/mp3-downloader/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/usr/local/lib/node_modules/mp3-downloader/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/usr/local/lib/node_modules/mp3-downloader/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/usr/local/lib/node_modules/mp3-downloader/node_modules/rx-lite/rx.lite.js:5741:44)
    at AnonymousObservable.innerSubscribe [as _subscribe] (/usr/local/lib/node_modules/mp3-downloader/node_modules/rx-lite/rx.lite.js:5755:9)
```

**Comment by Jense5** [comment]
This is fixed in your pull request, right?

**Comment by RobinHaveneers** [comment]
Yup
